
services:
  xcat:
    image: cdac_xcat_alma8:2.17.0
    env_file:
      - .env
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /drbd/xcatdata:/xcatdata       # Bind the DRBD mount point to /xcatdata in the container
      - /drbd/var_log_xcat:/var/log/xcat
      - /drbd/xcat_mysqldata:/var/lib/mysql
      - /drbd/xcatcont_sshkey/.ssh:/root/.ssh
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
           - node.labels.xcat_master == true
    network_mode: host
